"""Retail Customer Analytics - Lightweight, validated probabilistic pipeline."""

from .features import (
    _basket_composition_features,
    _breadth_features,
    _build_trips_for_snapshot,
    _category_affinity_features,
    _core_customer_features,
    _promo_features,
    _trend_features,
    _window_features,
    build_customer_features,
    build_customer_snapshot,
)
from .ingestion import (
    CURRENCY_SYMBOLS,
    DATE_FORMATS,
    DEFAULT_CURRENCY,
    ID_COLUMNS,
    REQUIRED_COLUMNS,
    TEXT_COLUMNS,
    clean_lines,
    fmt_currency,
    fmt_number,
    fmt_pct,
    load_lines,
    load_lines_from_dataframe,
    parse_dates,
    prepare_transaction_frame,
    structural_checks,
)

__all__ = [
    "REQUIRED_COLUMNS",
    "ID_COLUMNS",
    "TEXT_COLUMNS",
    "DATE_FORMATS",
    "DEFAULT_CURRENCY",
    "CURRENCY_SYMBOLS",
    "parse_dates",
    "load_lines",
    "clean_lines",
    "structural_checks",
    "prepare_transaction_frame",
    "load_lines_from_dataframe",
    "fmt_currency",
    "fmt_number",
    "fmt_pct",
    "build_customer_snapshot",
    "build_customer_features",
    "_build_trips_for_snapshot",
    "_core_customer_features",
    "_window_features",
    "_breadth_features",
    "_promo_features",
    "_category_affinity_features",
    "_trend_features",
    "_basket_composition_features",
]

__version__ = "0.1.0"
